### ISSUE TITLE
https://www.hotdoy.ca/edbearing/ not available

### ISSUE THREAD

**Issue by Jibsman** [hotdoy/EDbearing#1]
Is the site down? Changed? I rely on this tool to find locations!  Can I help somehow if there's a problem supporting the site?

**Comment by vincentrouleau** [comment]
I moved it a while back and really didn't really pay attention to it for a while now. 
You can still reach it at https://hotdoy.org/elite/
But some links might be broken so you'll probably have to check the URLs.
 I'll check if I can host it properly and fix the links sometimes this week but it's gonna be tight.

**Comment by Jibsman** [comment]
MalwareBytes tells me not to visit the site due to phishing. I wonder what's up with that?


I also found one here: https://edbearingcalc.neocities.org/

On March 10, 2020 at 7:38 PM, hotdoy <notifications@github.com> wrote:



I moved it a while back and really didn't really pay attention to it for a while now.
You can still reach it at http://hotdoy.org/elite/
But some links might be broken so you'll probably have to check the URLs.
I'll check if I can host it properly and fix the links sometimes this week but it's gonna be tight.

**Comment by Jibsman** [comment]
By the way there are many of us that use this tool. Do you have a PayPal or other method to help support it? If it's legit and working I'd pop a fiver to keep it going.
Happy Daze

On March 10, 2020 at 7:38 PM, hotdoy <notifications@github.com> wrote:



I moved it a while back and really didn't really pay attention to it for a while now.
You can still reach it at http://hotdoy.org/elite/
But some links might be broken so you'll probably have to check the URLs.
I'll check if I can host it properly and fix the links sometimes this week but it's gonna be tight.

**Comment by vincentrouleau** [comment]
The auto https is probably disabled and I'm collecting some data (for the destination submitting) so that's probably the phishing warning. 

There is a "donate" button if you scroll down the page if you feel like donating. 

I'll keep you posted for the move. 
Might get a new domain of just move it to a sub.

**Comment by vincentrouleau** [comment]
Everything has been moved and tested to [elite.hotdoy.org](https://elite.hotdoy.org)

**Comment by vincentrouleau** [comment]
I've also updated the links on the Frontier forum, edcodex elite tools, posted on reddit and sent an email to Canonn Research Group webmaster.
